package com.hersac.fastfoot.ui;

import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import com.hersac.fastfoot.models.Clientes;
import com.hersac.fastfoot.models.Menu;
import com.hersac.fastfoot.models.Pedido;
import com.hersac.fastfoot.services.ClientesService;
import com.hersac.fastfoot.services.MenuService;
import com.hersac.fastfoot.services.PedidoService;

public class Root extends javax.swing.JFrame {

    private ClientesService clienteServ = new ClientesService();
    private PedidoService pedidoService = new PedidoService();

    /**
     * Creates new form Root
     */
    public Root() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        ModalEditarPedido modalEditar = new ModalEditarPedido();
        ModalEliminarPedido modalEliminar = new ModalEliminarPedido();
        modalEditar.setVisible(false);
        modalEliminar.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(247, 226, 152));

        jPanel4.setBackground(new java.awt.Color(247, 226, 152));

        jLabel2.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(253, 30, 68));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Solicitud de pedidos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addContainerGap()));

        jLayeredPane1.setLayout(new java.awt.GridLayout(1, 2, 18, 0));

        jPanel1.setBackground(new java.awt.Color(250, 252, 238));

        jLayeredPane2.setLayout(new java.awt.GridLayout(2, 2, 18, 18));

        jLabel5.setForeground(new java.awt.Color(253, 30, 68));
        jLabel5.setText(menus.get(0).getNombre());
        jPanel12.add(jLabel5);

        jLabel8.setForeground(new java.awt.Color(253, 30, 68));
        jLabel8.setText(formatearComoMoneda(menus.get(0).getPrecio()));
        jPanel12.add(jLabel8);

        jLabel14.setForeground(new java.awt.Color(140, 140, 140));
        jLabel14.setText("Cantidad: ");
        jPanel16.add(jLabel14);

        jTextField4.setBackground(new java.awt.Color(250, 252, 238));
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        jTextField4.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel16.add(jTextField4);

        jPanel24.setBackground(new java.awt.Color(250, 252, 238));
        // jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // jLabel18.setIcon(new
        // javax.swing.ImageIcon(getClass().getResource("/menu1.jpg"))); // NOI18N
        jLabel18.setPreferredSize(new java.awt.Dimension(50, 50));
        jLabel18.setText("");
        jPanel24.add(jLabel18);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap()));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        jLayeredPane2.add(jPanel5);

        jLabel7.setForeground(new java.awt.Color(253, 30, 68));
        jLabel7.setText(menus.get(1).getNombre());
        jPanel13.add(jLabel7);

        jLabel9.setForeground(new java.awt.Color(253, 30, 68));
        jLabel9.setText(formatearComoMoneda(menus.get(1).getPrecio()));
        jPanel13.add(jLabel9);

        jLabel15.setForeground(new java.awt.Color(140, 140, 140));
        jLabel15.setText("Cantidad: ");
        jPanel17.add(jLabel15);

        jTextField5.setBackground(new java.awt.Color(250, 252, 238));
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        jTextField5.setPreferredSize(new java.awt.Dimension(40, 20));

        jPanel17.add(jTextField5);

        jPanel21.setBackground(new java.awt.Color(250, 252, 238));
        // jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // jLabel19.setIcon(new
        // javax.swing.ImageIcon(getClass().getResource("/menu2.jpg"))); // NOI18N
        jLabel19.setPreferredSize(new java.awt.Dimension(50, 50));
        jLabel19.setText("");
        jPanel21.add(jLabel19);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        jLayeredPane2.add(jPanel6);

        jLabel10.setForeground(new java.awt.Color(253, 30, 68));
        jLabel10.setText(menus.get(2).getNombre());
        jPanel14.add(jLabel10);

        jLabel11.setForeground(new java.awt.Color(253, 30, 68));
        jLabel11.setText(formatearComoMoneda(menus.get(0).getPrecio()));
        jPanel14.add(jLabel11);

        jLabel16.setForeground(new java.awt.Color(140, 140, 140));
        jLabel16.setText("Cantidad: ");
        jPanel18.add(jLabel16);

        jTextField6.setBackground(new java.awt.Color(250, 252, 238));
        jTextField6.setForeground(new java.awt.Color(0, 0, 0));
        jTextField6.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel18.add(jTextField6);

        jPanel22.setBackground(new java.awt.Color(250, 252, 238));

        // jLabel20.setIcon(new
        // javax.swing.ImageIcon(getClass().getResource("/menu3.jpg"))); // NOI18N
        jLabel20.setPreferredSize(new java.awt.Dimension(50, 50));
        jLabel20.setText("");
        jLabel20.setPreferredSize(new java.awt.Dimension(310, 256));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
                jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE));
        jPanel22Layout.setVerticalGroup(
                jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 240,
                                                Short.MAX_VALUE))
                                .addContainerGap()));
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        jLayeredPane2.add(jPanel7);

        jLabel12.setForeground(new java.awt.Color(253, 30, 68));
        jLabel12.setText(menus.get(3).getNombre());
        jPanel15.add(jLabel12);

        jLabel13.setForeground(new java.awt.Color(253, 30, 68));
        jLabel13.setText(formatearComoMoneda(menus.get(0).getPrecio()));
        jPanel15.add(jLabel13);

        jLabel17.setForeground(new java.awt.Color(140, 140, 140));
        jLabel17.setText("Cantidad: ");
        jPanel19.add(jLabel17);

        jTextField7.setBackground(new java.awt.Color(250, 252, 238));
        jTextField7.setForeground(new java.awt.Color(0, 0, 0));
        jTextField7.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel19.add(jTextField7);

        jPanel23.setBackground(new java.awt.Color(250, 252, 238));

        // jLabel21.setIcon(new
        // javax.swing.ImageIcon(getClass().getResource("/menu4.jpg"))); // NOI18N
        jLabel21.setPreferredSize(new java.awt.Dimension(50, 50));
        jLabel21.setText("");
        jLabel21.setMaximumSize(new java.awt.Dimension(310, 256));
        jLabel21.setName(""); // NOI18N
        jLabel21.setPreferredSize(new java.awt.Dimension(310, 256));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
                jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE));
        jPanel23Layout.setVerticalGroup(
                jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                                .addContainerGap()));
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        jLayeredPane2.add(jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLayeredPane2)
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLayeredPane2)
                                .addContainerGap()));

        jLayeredPane1.add(jPanel1);

        jPanel3.setBackground(new java.awt.Color(250, 252, 238));

        jLabel6.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(253, 30, 68));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REGISTRO DE CLIENTE");

        jPanel9.setBackground(new java.awt.Color(250, 252, 238));

        jLabel1.setForeground(new java.awt.Color(140, 140, 140));
        jLabel1.setText("Nro. Documento:");

        jLabel3.setForeground(new java.awt.Color(140, 140, 140));
        jLabel3.setText("ID Servicio:");

        jLabel4.setForeground(new java.awt.Color(140, 140, 140));
        jLabel4.setText("Nombre:");

        jTextField1.setBackground(new java.awt.Color(250, 252, 238));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setDisabledTextColor(new java.awt.Color(253, 30, 68));

        jTextField2.setBackground(new java.awt.Color(250, 252, 238));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField2.setDisabledTextColor(new java.awt.Color(253, 30, 68));

        jTextField3.setBackground(new java.awt.Color(250, 252, 238));
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField3.setDisabledTextColor(new java.awt.Color(253, 30, 68));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField1))
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField3))
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField2)))
                                .addContainerGap()));
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel10.setBackground(new java.awt.Color(250, 252, 238));
        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton5.setBackground(new java.awt.Color(253, 30, 68));
        jButton5.setForeground(new java.awt.Color(250, 252, 238));
        jButton5.setText("AGREGAR");

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPedido();
                jTable1.setModel(obtenerTabla());
            }
        });

        jPanel10.add(jButton5);

        jButton6.setBackground(new java.awt.Color(253, 30, 68));
        jButton6.setForeground(new java.awt.Color(250, 252, 238));
        jButton6.setText("ELIMINAR");
        jPanel10.add(jButton6);

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent ent) {
                modalEliminar.setVisible(true);
            }
        });

        jButton7.setBackground(new java.awt.Color(253, 30, 68));
        jButton7.setForeground(new java.awt.Color(250, 252, 238));
        jButton7.setText("ACTUALIZAR");
        jPanel10.add(jButton7);

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent ent) {
                modalEditar.setVisible(true);
            }
        });

        jButton8.setBackground(new java.awt.Color(253, 30, 68));
        jButton8.setForeground(new java.awt.Color(250, 252, 238));
        jButton8.setText("LIMPIAR");

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarCampos();
                jTable1.setModel(obtenerTabla());

            }
        });

        jPanel10.add(jButton8);

        jPanel11.setBackground(new java.awt.Color(250, 252, 238));

        jTable1.setBackground(new java.awt.Color(250, 252, 238));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(obtenerTabla());

        jTable1.setSelectionBackground(new java.awt.Color(250, 252, 238));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanel11Layout.setVerticalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(126, Short.MAX_VALUE)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        jLayeredPane1.add(jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLayeredPane1)
                                .addContainerGap()));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLayeredPane1)
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // LOGICA
    List<Menu> menus = listarMenus();
    List<Clientes> clientes = listarClientes();
    List<Pedido> pedidos = listarPedidos();

    public List<Clientes> listarClientes() {
        try {
            ClientesService menuService = new ClientesService();
            return menuService.getClientes();
        } catch (Exception e) {
            System.out.println("Error al listar clientes");
            return null;
        }
    }

    public List<Pedido> listarPedidos() {
        try {
            PedidoService pedidoService = new PedidoService();
            return pedidoService.getPedidos();
        } catch (Exception e) {
            System.out.println("Error al listar pedidos");
            return null;
        }
    }

    public List<Menu> listarMenus() {
        try {
            MenuService menuService = new MenuService();
            return menuService.getMenus();
        } catch (Exception e) {
            System.out.println("Error al listar Menus");
            return null;
        }
    }

    public TableModel obtenerTabla() {
        DefaultTableModel dtm = new DefaultTableModel();
        String[] headers = { "ID", "NOMBRE", "NRO. DOCUMENTO", "MENU 1", "MENU 2", "MENU 3",
                "MENU 4", "TOTAL" };
        dtm.setDataVector(listarPedidosTabla(), headers);
        return dtm;
    }

    public Object[][] listarPedidosTabla() {
        try {
            List<Pedido> pedidos = listarPedidos();
            List<Menu> menus = listarMenus();
            ArrayList<Double> preciosMenu = new ArrayList<>();

            menus.forEach((menu) -> {
                preciosMenu.add(menu.getPrecio());
            });
            Object[][] data = new Object[pedidos.size()][8];
            int i = 0;
            for (Pedido pedido : pedidos) {
                Double valorTotal = 0.0;

                data[i][0] = pedido.getPedidoId();
                data[i][1] = pedido.getClientesId().getNombre();
                data[i][2] = pedido.getClientesId().getNumeroDocumento();
                data[i][3] = pedido.getCantidadMenu1();
                data[i][4] = pedido.getCantidadMenu2();
                data[i][5] = pedido.getCantidadMenu3();
                data[i][6] = pedido.getCantidadMenu4();

                valorTotal = valorTotal + ValorCantidadxMenu(preciosMenu.get(0), pedido.getCantidadMenu1());
                valorTotal = valorTotal + ValorCantidadxMenu(preciosMenu.get(1), pedido.getCantidadMenu2());
                valorTotal = valorTotal + ValorCantidadxMenu(preciosMenu.get(2), pedido.getCantidadMenu3());
                valorTotal = valorTotal + ValorCantidadxMenu(preciosMenu.get(3), pedido.getCantidadMenu4());

                data[i][7] = formatearComoMoneda(valorTotal);
                i++;
            }
            return data;
        } catch (Exception e) {
            System.out.println("Error al listar pedidos");
            return null;
        }
    }

    private Double ValorCantidadxMenu(Double valor, int cantidad) {
        return valor * cantidad;
    }

    private String formatearComoMoneda(double valor) {
        DecimalFormat formatoMoneda = new DecimalFormat("#,##0.00");
        return "$ " + formatoMoneda.format(valor);
    }

    public void limpiarCampos() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
    }

    public void agregarPedido() {
        Clientes nuevoCliente = new Clientes();
        Pedido nuevoPedido = new Pedido();

        try {
            nuevoCliente.setNombre(jTextField2.getText());
            nuevoCliente.setNumeroDocumento(jTextField3.getText());

            Clientes clienteExistente = clienteServ.findClientesByIdentificacion(nuevoCliente.getNumeroDocumento());

            if (clienteExistente != null) {
                System.out.println("El cliente ya existe");
                return;
            }

            if (nuevoCliente.getNombre().isEmpty() || nuevoCliente.getNumeroDocumento().isEmpty()) {
                System.out.println("Debe digitar un nombre y una identificacion para el cliente");
                return;
            }

            clienteServ.addCliente(nuevoCliente);
            System.out.println("Cliente agregado");
        } catch (Exception e) {
            System.out.println("Error al agregar Cliente");
        }

        try {
            Clientes clienteGuardado = clienteServ.findClientesByIdentificacion(jTextField3.getText());
            int cantidad1 = jTextField4.getText().isEmpty() ? 0 : Integer.parseInt(jTextField4.getText());
            int cantidad2 = jTextField5.getText().isEmpty() ? 0 : Integer.parseInt(jTextField5.getText());
            int cantidad3 = jTextField6.getText().isEmpty() ? 0 : Integer.parseInt(jTextField6.getText());
            int cantidad4 = jTextField7.getText().isEmpty() ? 0 : Integer.parseInt(jTextField7.getText());
            nuevoPedido.setClientesId(clienteGuardado);
            nuevoPedido.setCantidadMenu1(cantidad1);
            nuevoPedido.setCantidadMenu2(cantidad2);
            nuevoPedido.setCantidadMenu3(cantidad3);
            nuevoPedido.setCantidadMenu4(cantidad4);
            nuevoPedido.setEstado(true);
            pedidoService.addPedido(nuevoPedido);
            limpiarCampos();
        } catch (Exception e) {
            System.out.println("Error al agregar pedido");
        }

    }

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */

    /*
     * public static void main(String args[]) {
     * try {
     * for (javax.swing.UIManager.LookAndFeelInfo info :
     * javax.swing.UIManager.getInstalledLookAndFeels()) {
     * if ("Nimbus".equals(info.getName())) {
     * javax.swing.UIManager.setLookAndFeel(info.getClassName());
     * break;
     * }
     * }
     * } catch (ClassNotFoundException ex) {
     * java.util.logging.Logger.getLogger(Root.class.getName()).log(java.util.
     * logging.Level.SEVERE, null, ex);
     * } catch (InstantiationException ex) {
     * java.util.logging.Logger.getLogger(Root.class.getName()).log(java.util.
     * logging.Level.SEVERE, null, ex);
     * } catch (IllegalAccessException ex) {
     * java.util.logging.Logger.getLogger(Root.class.getName()).log(java.util.
     * logging.Level.SEVERE, null, ex);
     * } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     * java.util.logging.Logger.getLogger(Root.class.getName()).log(java.util.
     * logging.Level.SEVERE, null, ex);
     * }
     * 
     * java.awt.EventQueue.invokeLater(new Runnable() {
     * public void run() {
     * new Root().setVisible(true);
     * }
     * });
     * }
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
